[program:ultimate_dca_bot]
directory=/opt/ultimate_dca_bot
command=/opt/ultimate_dca_bot/.venv/bin/python bot.py
autostart=true
autorestart=true
startsecs=10
startretries=3
stopasgroup=true
killasgroup=true
stdout_logfile=/opt/ultimate_dca_bot/logs/supervisor_stdout.log
stderr_logfile=/opt/ultimate_dca_bot/logs/supervisor_stderr.log
environment=PYTHONUNBUFFERED="1"
